Handle warning return codes of tar command
The return code 1 is just a warning and can be ignored

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -230,6 +230,13 @@ jobs:
             --exclude=.git --exclude=.github \
             .
 
+          export rc=$?
+          if [ $rc -eq 1 ]; then
+            echo "some files were changed during reading"
+          elif [ $rc -ge 2 ]; then
+            echo "building tar failed"
+          fi
+
       - name: Upload artifact
         uses: actions/upload-artifact@v3
         with:
