Ignore all exit codes of tar command

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -228,14 +228,8 @@ jobs:
             --directory $path \
             -cf "${{ runner.temp }}/page_artifact.tar" \
             --exclude=.git --exclude=.github \
-            .
+            . || true # prevents the command from returning 1 as a warning which fails the entire workflow
 
-          export rc=$?
-          if [ $rc -eq 1 ]; then
-            echo "some files were changed during reading"
-          elif [ $rc -ge 2 ]; then
-            echo "building tar failed"
-          fi
 
       - name: Upload artifact
         uses: actions/upload-artifact@v3
